# Generated by Django 5.0 on 2025-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
