# Generated by Django 5.0 on 2025-06-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
