# Generated by Django 5.0 on 2025-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_task_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
